pr: none

pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: |
    set -e
    docker build -t opendbc .
    docker run opendbc bash -c "python -m unittest discover opendbc"

  displayName: 'Run Tests'
