# Extra cars that aren't supportable, or support is a work-in-progress, or may be available in custom forks

[[platforms]]
name = "Hyundai Palisade 2023-24"
package = "HDA1"
status = "WIP"
link = "#hkg"

[[platforms]]
name = "Kia Telluride 2023-24"
package = "HDA1"
status = "WIP"
link = "#hkg"
