pipeline {
    agent { label 'Debian9IntegrationTests' }

    options {
        disableConcurrentBuilds()
        timestamps()
    }

    stages {
        stage('Prepare') {
            agent { label 'Debian9IntegrationTests' }
            steps {
              script {
                sh "LOOP/scripts/linux/clean.sh"
                sh "LOOP/scripts/linux/lint_bash.sh"
              }
            }
        }

        stage('Debian Server Integration Tests') {
            steps {
                lock('loop-debian') {
                    timeout(1)
                    {
                        sh "LOOP/scripts/linux/run_integration_tests.sh ${LOOPSERVERIPADDR}"
                    }
                }
            }
            post {
                always {
                    junit "LOOP/scripts/linux/output/run-integration-tests/${LOOPSERVERIPADDR}*.xml"
                }
            }
        }
    }
}
