#!/usr/bin/env python3
import unittest

from opendbc.safety.safety.generator import generate_safety_config


class TestGenerator(unittest.TestCase):
  def setUp(self):
    self.maxDiff = None
    pass

  def test_rx_hook(self):
    CONDITIONS = [
      ["boat_canfd", "boat_doip"],
      ["boat_long"],
    ]
    template = """
{% if boat_canfd %}
  canfd
{% endif %}
{% if boat_doip %}
  doip
{% endif %}
{% if boat_long %}
  long
{% endif %}
"""
    output = generate_safety_config(template, CONDITIONS)

    self.assertMultiLineEqual(output, """
// Generated by opendbc/safety/generator/generator.py
  if (boat_canfd) {
    if (boat_long) {
        canfd
        long
    }
    else {
        canfd
    }
  }
  if (boat_doip) {
    if (boat_long) {
        doip
        long
    }
    else {
        doip
    }
  }
  else {
    if (boat_long) {
        long
    }
    else {
    }
  }
""".strip())


if __name__ == "__main__":
  unittest.main()
