import os
import re
import subprocess
import tempfile
from pathlib import Path

from cffi import FFI

from opendbc.safety import LEN_TO_DLC

libsafety_dir = os.path.dirname(os.path.abspath(__file__))


def _build_libsafety(release: bool = False) -> str:
  """Compile libsafety.so to a temp file and return its path."""
  root = str(Path(libsafety_dir).parents[3])
  safety_c = os.path.join(libsafety_dir, "safety.c")

  cflags = [
    '-Wall', '-Wextra', '-Werror', '-nostdlib', '-fno-builtin',
    '-std=gnu11', '-Wfatal-errors', '-Wno-pointer-to-int-cast',
    '-g', '-O0', '-fno-omit-frame-pointer',
  ]
  # Coverage must exclude the branches inserted by UBSan.
  if os.environ.get("SAFETY_COVERAGE") == "1":
    ldflags = ['-fprofile-arcs', '-ftest-coverage'] if not release else []
  else:
    ldflags = ['-fsanitize=undefined', '-fno-sanitize-recover=undefined']
  cflags += ldflags
  if not release:
    cflags += ['-DALLOW_DEBUG']

  fd, safety_os = tempfile.mkstemp(suffix='.os', dir=libsafety_dir)
  os.close(fd)
  fd, libsafety_so = tempfile.mkstemp(suffix='.so')
  os.close(fd)

  subprocess.check_call(['cc', '-fPIC', *cflags, '-I', root, '-c', safety_c, '-o', safety_os])
  subprocess.check_call(['cc', '-shared', safety_os, '-o', libsafety_so, *ldflags])
  return libsafety_so


ffi = FFI()

safety_dir = Path(libsafety_dir).parents[1]
can_header = (safety_dir / "can.h").read_text()
can_defines = re.findall(r"^#define CANPACKET_\w+ \d+U?", can_header, re.MULTILINE)
can_struct, = re.findall(r"typedef struct \{[^}]+\}[^;]+ CANPacket_t;", can_header)
# CFFI takes packing as an option rather than a GCC attribute.
can_struct = re.sub(r"__attribute__\(\(.*\)\)", "", can_struct)
ffi.cdef("\n".join([*can_defines, can_struct]), packed=True)
class CANPacket:
  pass

# Extract the public safety API and test helper signatures from their C sources.
for path, name, terminator in (
  (safety_dir / "declarations.h", r"(?:safety_\w+|set_safety_hooks|get_longitudinal_allowed)", ";"),
  (safety_dir / "ignition.h", r"\w+", "{"),
  (Path(libsafety_dir) / "safety.c", r"\w+", "{"),
):
  signatures = re.findall(rf"^((?:bool|int|float|void|uint32_t) {name}\([^()]*\))\s*{re.escape(terminator)}",
                          path.read_text(), re.MULTILINE)
  ffi.cdef("\n".join(f"{signature};" for signature in signatures))

# This function is generated by mutation.py rather than defined in the sources above.
ffi.cdef("void mutation_set_active_mutant(int id);")

class LibSafety:
  pass
libsafety: LibSafety

def load(path):
  global libsafety
  libsafety = ffi.dlopen(str(path))

def __getattr__(name):
  if name == "libsafety":
    load(_build_libsafety())
    return libsafety
  raise AttributeError(name)

def make_CANPacket(addr: int, bus: int, dat):
  ret = ffi.new('CANPacket_t *')
  ret[0].extended = 1 if addr >= 0x800 else 0
  ret[0].addr = addr
  ret[0].data_len_code = LEN_TO_DLC[len(dat)]
  ret[0].bus = bus
  ret[0].data = bytes(dat)
  return ret
