name: Re-draft on review
on:
  pull_request_review:
    types: [submitted]

jobs:
  redraft:
    if: github.event.review.state == 'changes_requested'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - run: gh pr ready --undo "${{ github.event.pull_request.number }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
